"""add shares dilution and scorecard columns

Revision ID: 3dad52a76c82
Revises: 77c4e2fb8a63
Create Date: 2026-06-29 11:34:30.885942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dad52a76c82'
down_revision: Union[str, Sequence[str], None] = '77c4e2fb8a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_financials_calculated', sa.Column('revenue_growth_yoy', sa.Numeric(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('revenue_cagr_5y', sa.Numeric(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('gross_margin', sa.Numeric(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('gross_margin_change_yoy', sa.Numeric(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('shares_outstanding', sa.Numeric(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('share_count_change_yoy', sa.Numeric(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('gross_margin_change_5y', sa.Numeric(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('operating_margin_change_5y', sa.Numeric(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('net_margin_change_5y', sa.Numeric(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('share_count_change_5y', sa.Numeric(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('total_debt_change_5y', sa.Numeric(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('score_margin_growth', sa.Integer(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('score_low_dilution', sa.Integer(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('score_capital_efficiency', sa.Integer(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('score_overall', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_financials_calculated', 'score_overall')
    op.drop_column('company_financials_calculated', 'score_capital_efficiency')
    op.drop_column('company_financials_calculated', 'score_low_dilution')
    op.drop_column('company_financials_calculated', 'score_margin_growth')
    op.drop_column('company_financials_calculated', 'total_debt_change_5y')
    op.drop_column('company_financials_calculated', 'share_count_change_5y')
    op.drop_column('company_financials_calculated', 'net_margin_change_5y')
    op.drop_column('company_financials_calculated', 'operating_margin_change_5y')
    op.drop_column('company_financials_calculated', 'gross_margin_change_5y')
    op.drop_column('company_financials_calculated', 'share_count_change_yoy')
    op.drop_column('company_financials_calculated', 'shares_outstanding')
    op.drop_column('company_financials_calculated', 'gross_margin_change_yoy')
    op.drop_column('company_financials_calculated', 'gross_margin')
    op.drop_column('company_financials_calculated', 'revenue_cagr_5y')
    op.drop_column('company_financials_calculated', 'revenue_growth_yoy')
    # ### end Alembic commands ###
