"""add margin columns

Revision ID: 77c4e2fb8a63
Revises: 88b9db5215d9
Create Date: 2026-06-29 09:22:04.058745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c4e2fb8a63'
down_revision: Union[str, Sequence[str], None] = '88b9db5215d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_financials_calculated', sa.Column('operating_margin', sa.Numeric(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('net_margin', sa.Numeric(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('operating_margin_change_yoy', sa.Numeric(), nullable=True))
    op.add_column('company_financials_calculated', sa.Column('net_margin_change_yoy', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_financials_calculated', 'net_margin_change_yoy')
    op.drop_column('company_financials_calculated', 'operating_margin_change_yoy')
    op.drop_column('company_financials_calculated', 'net_margin')
    op.drop_column('company_financials_calculated', 'operating_margin')
    # ### end Alembic commands ###
