"""initial schema

Revision ID: 88b9db5215d9
Revises: 
Create Date: 2026-06-29 07:56:19.715305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88b9db5215d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('stock_code', sa.String(length=6), nullable=False),
    sa.Column('corp_name', sa.String(length=200), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('dart_modify_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('corp_code')
    )
    op.create_index(op.f('ix_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=False)
    op.create_index(op.f('ix_companies_stock_code'), 'companies', ['stock_code'], unique=True)
    op.create_table('dart_api_call_log',
    sa.Column('call_date', sa.Date(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('call_date')
    )
    op.create_table('screening_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('fiscal_year_end', sa.Integer(), nullable=False),
    sa.Column('history_years', sa.Integer(), nullable=False),
    sa.Column('fs_div_preference', sa.String(length=3), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('company_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_financials_calculated',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('screening_run_id', sa.Integer(), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('reprt_code', sa.String(length=5), nullable=False),
    sa.Column('fs_div_used', sa.String(length=3), nullable=True),
    sa.Column('revenue', sa.Numeric(), nullable=True),
    sa.Column('gross_profit', sa.Numeric(), nullable=True),
    sa.Column('operating_income', sa.Numeric(), nullable=True),
    sa.Column('net_income', sa.Numeric(), nullable=True),
    sa.Column('total_assets', sa.Numeric(), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(), nullable=True),
    sa.Column('total_equity', sa.Numeric(), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(), nullable=True),
    sa.Column('capex', sa.Numeric(), nullable=True),
    sa.Column('depreciation_amortization', sa.Numeric(), nullable=True),
    sa.Column('depreciation_source', sa.String(length=20), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(), nullable=True),
    sa.Column('reinvestment_ratio_capex_da', sa.Numeric(), nullable=True),
    sa.Column('reinvestment_ratio_capex_ocf', sa.Numeric(), nullable=True),
    sa.Column('short_term_borrowings', sa.Numeric(), nullable=True),
    sa.Column('long_term_borrowings', sa.Numeric(), nullable=True),
    sa.Column('total_debt', sa.Numeric(), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(), nullable=True),
    sa.Column('equity_impaired', sa.Boolean(), nullable=False),
    sa.Column('has_convertible_instruments', sa.Boolean(), nullable=False),
    sa.Column('convertible_instruments_value', sa.Numeric(), nullable=True),
    sa.Column('gross_profit_growth_yoy', sa.Numeric(), nullable=True),
    sa.Column('operating_income_growth_yoy', sa.Numeric(), nullable=True),
    sa.Column('net_income_growth_yoy', sa.Numeric(), nullable=True),
    sa.Column('gross_profit_cagr_5y', sa.Numeric(), nullable=True),
    sa.Column('operating_income_cagr_5y', sa.Numeric(), nullable=True),
    sa.Column('net_income_cagr_5y', sa.Numeric(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corp_code'], ['companies.corp_code'], ),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('screening_run_id', 'corp_code', 'fiscal_year', 'reprt_code', name='uq_cfc_run_corp_year_reprt')
    )
    op.create_index(op.f('ix_company_financials_calculated_corp_code'), 'company_financials_calculated', ['corp_code'], unique=False)
    op.create_index(op.f('ix_company_financials_calculated_screening_run_id'), 'company_financials_calculated', ['screening_run_id'], unique=False)
    op.create_table('screening_run_companies',
    sa.Column('screening_run_id', sa.Integer(), nullable=False),
    sa.Column('corp_code', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['corp_code'], ['companies.corp_code'], ),
    sa.ForeignKeyConstraint(['screening_run_id'], ['screening_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('screening_run_id', 'corp_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screening_run_companies')
    op.drop_index(op.f('ix_company_financials_calculated_screening_run_id'), table_name='company_financials_calculated')
    op.drop_index(op.f('ix_company_financials_calculated_corp_code'), table_name='company_financials_calculated')
    op.drop_table('company_financials_calculated')
    op.drop_table('screening_runs')
    op.drop_table('dart_api_call_log')
    op.drop_index(op.f('ix_companies_stock_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
